sources:
  donghuastream:
    name: "DonghuaStream"
    type: "wp-anime"
    base_url: "https://donghuastream.org"
    search_path: ""
  animekhor:
    name: "AnimeKhor"
    type: "wp-anime"
    base_url: "https://animekhor.com"
    search_path: ""

providers:
  rumble:
    name: "Rumble"
    processor: "rumble"

player:
  default: "vlc"  # can be mpv or vlc
  paths:
    mpv: "mpv"    # path to mpv executable
    vlc: "vlc"    # path to vlc executable
